on:
  push:
    branches: [main]

jobs:
  sync-to-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add fork remote with PAT
        run: |
          git remote add fork https://x-access-token:${{ secrets.FORK_PAT }}@github.com/gardenee/ckz-front.git
          git fetch fork || echo "fork fetch failed (OK if first time)"
          git push fork main --force
