on:
  push:
    branches: [main]

jobs:
  sync-to-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Echo PAT Length
        run: echo "${{ secrets.FORK_PAT }}" | wc -c

      - name: Add fork remote with PAT
        env:
          PAT: ${{ secrets.FORK_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add fork https://x-access-token:${PAT}@github.com/gardenee/ckz-front.git
          git push fork main --force
